// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SommOS.Entries.Infrastructure.DbContexts;

namespace SommOS.Entries.Infrastructure.PostgresMigrations
{
    [DbContext(typeof(EntriesContext))]
    partial class EntriesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SommOS.Entries.Core.Entities.EntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Country");

                    b.Property<DateTimeOffset>("DateAdded");

                    b.Property<DateTimeOffset>("LastModified");

                    b.Property<string>("Notes");

                    b.Property<string>("Producer");

                    b.Property<string>("Region");

                    b.Property<List<string>>("Tags");

                    b.Property<Guid>("UserId");

                    b.Property<string>("Vintage");

                    b.Property<string>("WineName");

                    b.HasKey("Id");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("SommOS.Entries.Core.Entities.EntryLabelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("EntryId");

                    b.Property<byte[]>("Image");

                    b.HasKey("Id");

                    b.HasIndex("EntryId")
                        .IsUnique();

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("SommOS.Entries.Core.Entities.VarietalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("EntryId");

                    b.Property<string>("Name");

                    b.Property<decimal>("Percentage");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.ToTable("Varietals");
                });

            modelBuilder.Entity("SommOS.Entries.Core.Entities.EntryLabelEntity", b =>
                {
                    b.HasOne("SommOS.Entries.Core.Entities.EntryEntity", "Entry")
                        .WithOne("WineLabel")
                        .HasForeignKey("SommOS.Entries.Core.Entities.EntryLabelEntity", "EntryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SommOS.Entries.Core.Entities.VarietalEntity", b =>
                {
                    b.HasOne("SommOS.Entries.Core.Entities.EntryEntity", "Entry")
                        .WithMany("Varietals")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
